#!/usr/bin/env bash
set -euo pipefail
shopt -s nullglob globstar

readonly TMP_DIR=$(mktemp -d)
readonly CONFIGS=(
  .zshrc
  .Xresources
  .vimrc
  .tmux.conf
  .vim
  .zsh
)

declare -A config_paths
config_paths=(
  [".zshrc"]=zshrc
  [".Xresources"]=rxvt/Xresources.xoria
  [".vimrc"]=vim/vimrc
  [".tmux.conf"]=tmux.conf
  [".vim"]=vim
  [".zsh"]=zsh
)

copy_to_backup() {
  mv "${HOME}/${1}" "${TMP_DIR}/${1}"
}

backup_configs() {
  local backup_required=false

  for config in "${CONFIGS[@]}"; do
    local path="${HOME}/$config"
    if [[ -f "$path" ]] || [[ -d "$path" ]]; then
      copy_to_backup "$config"
      backup_required=true
    fi
  done

  if [[ backup_required ]]; then
    echo "Created a backup at ${TMP_DIR}"
  else
    rm -rf "$TMPDIR"
  fi
}

link_configs() {
  for config in "${CONFIGS[@]}"; do
    ln -s "$PWD""/""${config_paths[$config]}" "$HOME""/""$config"
  done
}


main() {
  backup_configs
  link_configs

  exit 0
}

main
