#!/usr/bin/env bash

set -euo pipefail

if [[ $(uname -s) != "Darwin" ]]; then
  echo "Only MacOS is supported... exiting."
  exit 1
fi

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
touch "$HOME/.hushlogin"
mkdir -p "$HOME/Desktop/Screenshots"
exec "$script_dir/macos"
