#!/usr/bin/env bash
# Collects Nix garbage and removes stopped Docker containers and unused images.
#
# Usage: ,gc

set -euo pipefail

nix store gc
docker container prune --force
docker image prune --all --force
