#!/usr/bin/env bash
# Cleans up the system by collecting garbage and removing docker containers and images.
#
# Usage: ,gc

set -eou pipefail

nix-collect-garbage
docker rm $(docker ps -aq)
docker rmi $(docker images -aq)
