#!/usr/bin/env bash
#
# USAGE: ,ssh-init-term
#
# Sets term info on a remote server to allow for more advanced terminal features.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: ,ssh-init-term <host>" >&2
  exit 1
fi

infocmp -x | ssh -- "$1" tic -x -
